version: 2.0
automatedReviewActive: true
kodusConfigFileOverridesWebPreferences: true
pullRequestApprovalActive: true
isRequestChangesActive: false
reviewOptions:
  security: true
  code_style: true
  kody_rules: true
  refactoring: true
  error_handling: true
  maintainability: true
  potential_issues: true
  documentation_and_comments: true
  performance_and_optimization: true
  bug: true
  performance: true
  cross_file: true
summary:
  generatePRSummary: true
  customInstructions: ''
  behaviourForExistingDescription: 'concatenate'
suggestionControl:
  groupingMode: 'full'
  limitationType: 'pr'
  maxSuggestions: 9
  severityLevelFilter: 'medium'
baseBranches: []
ignorePaths:
  - 'yarn.lock'
  - 'package-lock.json'
  - 'package.json'
  - '.env'
  - '**/*.json'
